# -*- coding: utf-8 -*-
"""mean_var_std.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TT0XKn8fiaB3tz9oirOkSddOeAp94Cq3
"""

import numpy as np

def calculate(list):
    # Verifica que la lista tenga exactamente 9 elementos
    if len(list) != 9:
        raise ValueError("List must contain nine numbers.")

    # Convierte la lista en un array 3x3
    arr = np.array(list).reshape(3, 3)

    # Calcula todas las métricas
    calculations = {
        'mean': [arr.mean(axis=0).tolist(), arr.mean(axis=1).tolist(), arr.mean()],
        'variance': [arr.var(axis=0).tolist(), arr.var(axis=1).tolist(), arr.var()],
        'standard deviation': [arr.std(axis=0).tolist(), arr.std(axis=1).tolist(), arr.std()],
        'max': [arr.max(axis=0).tolist(), arr.max(axis=1).tolist(), arr.max()],
        'min': [arr.min(axis=0).tolist(), arr.min(axis=1).tolist(), arr.min()],
        'sum': [arr.sum(axis=0).tolist(), arr.sum(axis=1).tolist(), arr.sum()]
    }

    return calculations

from pprint import pprint

# Prueba con el ejemplo del ejercicio
pprint(calculate([0,1,2,3,4,5,6,7,8]))